(define (problem courier-problem)
    (:domain courier-world-domain)
    (:objects 
        c - courier
        N1 N2 N3 N4 N5 N6 N7 N8 N9 N10 N11 N12 N13 - location
        pizza sushi burrito curry beer soda taco - item
    )

    (:init
        (road N1 N2)
        (road N1 N6)
        (road N1 N9)
        (road N1 N12)
        (road N2 N1)
        (road N2 N3)
        (road N3 N2)
        (road N3 N4)
        (road N4 N5)
        (road N5 N2)
        (road N5 N6)
        (road N6 N1)
        (road N6 N7)
        (road N7 N6)
        (road N7 N8)
        (road N8 N7)
        (road N9 N1)
        (road N9 N10)
        (road N10 N9)
        (road N11 N9)
        (road N12 N11)
        (road N12 N13)
        (at c N9)
        (item-at pizza N12)
        (item-at sushi N2)
        (item-at curry N2)
        (item-at beer N3)
        (item-at soda N3)
        (item-at taco N6)
        (item-at burrito N6)
        (needs curry N11)
        (needs taco N8)
        (needs burrito N13)
        (needs soda N13)
        (needs sushi N5)
        (needs pizza N10)
        (needs beer N10)
        (= (fuel c) 20)
        (= (max-fuel c) 40)
        (= (length N1 N2) 2)
        (= (length N1 N6) 3)
        (= (length N1 N9) 4)
        (= (length N1 N12) 2)
        (= (length N2 N1) 2)
        (= (length N2 N3) 2)
        (= (length N3 N2) 2)
        (= (length N3 N4) 1)
        (= (length N4 N5) 2)
        (= (length N5 N2) 3)
        (= (length N5 N6) 2)
        (= (length N6 N1) 3)
        (= (length N6 N7) 2)
        (= (length N7 N6) 2)
        (= (length N7 N8) 2)
        (= (length N8 N7) 2)
        (= (length N9 N1) 4)
        (= (length N9 N10) 3)
        (= (length N10 N9) 3)
        (= (length N11 N9) 4)
        (= (length N12 N11) 3)
        (= (length N12 N13) 4)
    )

    (:goal (and
        (delivered N11 curry)
        (delivered N8 taco)
        (delivered N13 burrito)
        (delivered N13 soda)
        (delivered N5 sushi)
        (delivered N10 pizza)
        (delivered N10 beer)
    ))
)
